#!/usr/bin/python
import sys

filename= sys.argv
openfile = filename[1]

filer = open(openfile, 'r')
openfile= openfile.replace(".txt", "-fanged.txt")
file = open(openfile, "w")

for line in filer:
    str = line
    str = str.replace("[.]", ".")
    str = str.replace("hxxp", "http")
    str = str.replace("[AT]", "@")
    print str;
    file.write(str)

file.close()
filer.close()
